name: precommit

on: [pull_request]

jobs:
  # jest:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'
  #   - name: Cache
  #     uses: actions/cache@v2
  #     with:
  #       path: ./node_modules
  #       key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
  #   - name: Run Jest
  #     uses: landon-martin/code-coverage-commenter@v0.0.8
  #     with:
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       coverage-command: "npm run coverage"
  #       comment-title: "Source Unit Test Coverage Report"
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - run: npm install
    - name: Run Lint
      run: |
        npm run lint
