on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./output/music-organizer-js
            ./output/music-organizer-js-mac
            ./output/music-organizer-js.exe
