on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install Dependencies
        run: |
          npm install
      - name: Cache Node Source
        uses: actions/cache@v3
        with:
          path: ~/.nexe
          key: linux-nexe-cache
      - name: Build
        run: |
          npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./output/music-organizer-js
            ./output/music-organizer-js-mac
            ./output/music-organizer-js.exe
